fix the bugs in integration tests under all modules
This patch includes the following changes:
1. The main entry of the program is adjusted from <module>_scanner.py
under each module to main.py, so the test script cannot generate the
json file.
2. Fixed the import error in __main__.py under all modules.
3. Rename integration folder under docker module to integration_test to
keep naming consistent.

Based on the above changes, we have two ways to run these integration tests.
e.g., run the integration tests under cpp module:
1. Run "python3 -m cpp ./cpp/integration_test" under migrate-ease
   root folder with setting "PYTHONPATH=./migrate-ease/cpp".
2. Run "./test" script under ./migrate-ease/cpp/integration_test folder.

Change-Id: I9d2627441a4f34fd9b4cff8fdb7a5628006b9cb3

diff --git a/cpp/integration_test/test b/cpp/integration_test/test
--- a/cpp/integration_test/test
+++ b/cpp/integration_test/test
@@ -1,33 +1,21 @@
 #!/usr/bin/env bash
 
-test_root=$(cd `dirname $0`; pwd)
-cpp_scanner_dir="${test_root}/.."
-RED=$(printf '\033[0;31m')
-RED_BOLD=$(printf '\033[1;31m')
-RED_LIGHT=$(printf '\033[91m')
+script_dir=$(realpath "$(dirname "$0")")
+main_dir="${script_dir}/.."
 
 GREEN=$(printf '\033[0;32m')
-GREEN_BOLD=$(printf '\033[1;32m')
-GREEN_LIGHT=$(printf '\033[92m')
 ENDMARK=$(printf '\033[m')
 
-cases="$@"
-[[ "$cases" = "" ]] && cases=$(ls | grep "test_[0-9]*")
+# Note that you need to run it in the directory where the test script is located.
+test_folders="$*"
+[[ "$test_folders" = "" ]] && test_folders=$(find -L . -type d -name 'test_*')
 
-for c in $cases ; do
-
-    if [[ "$c" == "test_9" ]]; then
-        echo $GREEN"$c is deprecated, skip."$ENDMARK
-        continue
-    fi
-
+for c in $test_folders ; do
     echo "=============== Running $c ... ==============="
 
-    cd "$c"
-
+    cd "$script_dir"/"$c" || { echo "Failure"; exit 1; }
     if [[ -e "disabled" ]]; then
-        echo $GREEN"$c is disabled, skip."$ENDMARK
-        cd "$test_root"
+        echo "$GREEN""$c is disabled, skip.""$ENDMARK"
         continue
     fi
 
@@ -35,47 +23,42 @@ for c in $cases ; do
     if [[ -d "./aarch64" ]]; then
         archs+=" aarch64"
     fi
-
-
     if [[ -d "./armv8.6-a+sve2" ]]; then
         archs+=" armv8.6-a+sve2"
     fi
-
     if [[ "$archs" = "" ]]; then
-        echo $GREEN"$c is empty, skip."$ENDMARK
-        cd "$test_root"
+        echo "$GREEN""$c is empty, skip.""$ENDMARK"
         continue
     fi
 
     for arch in $archs; do
-        echo "running sub-test: $arch"
-
-        if [[ "$arch" = "armv8.6-a+sve2" ]]; then
-            for level in L1 L2; do
-                for compiler in gcc clang; do
-                    echo "running test for warning-level $level-$compiler"
-                    python3 "$test_root"/../cpp_scanner.py \
-                      --output-format json \
-                      --output "./$arch/$level-$compiler/$arch.json" \
-                      --arch "$arch" \
-                      --warning-level "$level" \
-                      --target-compiler "$compiler" \
-                      "./$arch/$level-$compiler"
-                    if [[ "$?" = "0" ]]; then
-                      python3 "$test_root"/scanner_diff.py \
-                        --src-dir "./$arch/$level-$compiler/" \
-                        --json-report "./$arch/$level-$compiler/$arch.json"
-                    fi
+        echo "running sub-test for $arch"
+        case "$arch" in
+            "armv8.6-a+sve2")
+                for level in L1 L2; do
+                    for compiler in gcc clang; do
+                        echo "running test for warning-level $level-$compiler"
+                        python3 "$main_dir"/__main__.py --output-format json \
+                          --output "./$arch/$level-$compiler/$arch.json" \
+                          --arch "$arch" --warning-level "$level" \
+                          --target-compiler "$compiler" "./$arch/$level-$compiler"
+                        if [[ $? -eq 0 ]]; then
+                            echo "running scanner diff"
+                            python3 "$script_dir"/scanner_diff.py \
+                              --src-dir "./$arch/$level-$compiler/" \
+                              --json-report "./$arch/$level-$compiler/$arch.json"
+                        fi
+                    done
                 done
-            done
-            continue
-        fi
-        python3 "$test_root"/../cpp_scanner.py --output-format json --output "./$arch/$arch.json" --arch "$arch" ./"$arch"
-
-        if [[ "$?" = "0" ]]; then
-            python3 "$test_root"/scanner_diff.py --src-dir "./$arch/" --json-report "./$arch/$arch.json"
-        fi
+                continue
+            ;;
+            *)
+                python3 "$main_dir"/__main__.py --output-format json --output "./$arch/$arch.json" --arch "$arch" ./"$arch"
+                if [[ $? -eq 0 ]]; then
+                    echo "running scanner diff"
+                    python3 "$script_dir"/scanner_diff.py --src-dir "./$arch/" --json-report "./$arch/$arch.json"
+                fi
+            ;;
+        esac
     done
-
-    cd "$test_root"
 done
